
#ifndef RB_OPEN_IMAGE_FEATURES
#define RB_OPEN_IMAGE_FEATURES

#define OPEN_IMAGE_PIXELATE 0
#define OPEN_IMAGE_INVERT 0
#define OPEN_IMAGE_SEPIA 0
#define OPEN_IMAGE_GRAYSCALE 0
#define OPEN_IMAGE_SOLARIZE 0
#define OPEN_IMAGE_CONTRAST 0
#define OPEN_IMAGE_COLOR_BALANCE 0
#define OPEN_IMAGE_CONVOLUTION_FILTER 0

#if OPEN_IMAGE_CONVOLUTION_FILTER
#define OPEN_IMAGE_BOX_BLUR 0
#define OPEN_IMAGE_GAUSSIAN_BLUR 0
#define OPEN_IMAGE_SHARPEN 0
#define OPEN_IMAGE_EDGE_DETECT 0
#define OPEN_IMAGE_EMBOSS 0
#define OPEN_IMAGE_BRIGHTEN 0
#define OPEN_IMAGE_BLUR 0
#define OPEN_IMAGE_LINE_DETECT 0

#endif /* OPEN_IMAGE_CONVOLUTION_FILTER */
#endif /* RB_OPEN_IMAGE_FEATURES */