
#ifndef RB_OPEN_IMAGE_FEATURES
#define RB_OPEN_IMAGE_FEATURES 1

#define OPEN_IMAGE_PIXELATE 1
#define OPEN_IMAGE_INVERT 1
#define OPEN_IMAGE_SEPIA 1
#define OPEN_IMAGE_GRAYSCALE 1
#define OPEN_IMAGE_SOLARIZE 1
#define OPEN_IMAGE_CONTRAST 1
#define OPEN_IMAGE_COLOR_BALANCE 1
#define OPEN_IMAGE_CONVOLUTION_FILTER 1

#if OPEN_IMAGE_CONVOLUTION_FILTER
#define OPEN_IMAGE_BOX_BLUR 1
#define OPEN_IMAGE_GAUSSIAN_BLUR 1
#define OPEN_IMAGE_SHARPEN 1
#define OPEN_IMAGE_EDGE_DETECT 1
#define OPEN_IMAGE_EMBOSS 1
#define OPEN_IMAGE_BRIGHTEN 1
#define OPEN_IMAGE_BLUR 1
#define OPEN_IMAGE_LINE_DETECT 1

#endif /* OPEN_IMAGE_CONVOLUTION_FILTER */
#endif /* RB_OPEN_IMAGE_FEATURES */